site_name: rhdh-local
site_description: RHDH Local
site_author: user:user
docs_dir: docs
plugins:
  - techdocs-core
nav:
  - "Welcome To RHDH Local": index.md
  - "Highlights Of Red Hat Developer Hub": features.md
  - "TechDocs Extensions": extensions.md

  
